### PR TITLE
Fix a mistranslation

### PR DESCRIPTION
**Pull request by ghost**
GitHub Issue (If applicable): #

## PR Type

What kind of change does this PR introduce?

## How changes were validated:

-
-
-

## Other information

Internal Issue (If applicable):

### CODE REVIEW

**Comment by pxee** [comment]
Screenshot from Microsoft Calculator (language: zh-CN)
image
image

**Comment by ghost** [comment]
Screenshots from Windows Calculator (language: zh-CN)
image
image

**Comment by ghost** [comment]
@ahoefling @anandprabhakar0507 @ashu9999 @carldebilly @jeromelaban

**Comment by jeromelaban** [comment]
Thanks for your contribution!

**Pull request merged**
