### PR TITLE
Fix Background color for xamarin platforms

### PR DESCRIPTION
**Pull request by ghost**
## Fixes #.
Background color on xamarin platforms

### Description of the changes:
- Since by default the background is pure white on iOS and Android, the buttons would blen id with the background 
- Background was set to light gray
-

### How changes were validated:

- Tested on iOS emulator (working from home) and windows desktop

### CODE REVIEW

**Review by dr1rrb — APPROVED** [review]
For next PR, please do not re-indent the full file, or create a separate commit for that. It's introducing lot of noise and it's harder to find the real changes.

**Comment by davidjohnoliver** [comment]
> For next PR, please do not re-indent the full file, or create a separate commit for that. It's introducing lot of noise and it's harder to find the real changes.

image

;)

**Comment by dr1rrb** [comment]
> 
> 
> > For next PR, please do not re-indent the full file, or create a separate commit for that. It's introducing lot of noise and it's harder to find the real changes.
> 
> image
> 
> ;)

I still don't understand why this settings is not saved ... I forget to restore it every time I would have need it :(

**Comment by davidjohnoliver** [comment]
> > > For next PR, please do not re-indent the full file, or create a separate commit for that. It's introducing lot of noise and it's harder to find the real changes.
> > 
> > 
> > image
> > ;)
> 
> I still don't understand why this settings is not saved ... I always forget to restore it each time I would need it :(

I always have to poke around the UI for 5 minutes to remember where it is

**Pull request merged**
